LIB-test-ncd-updates
PIH/openmrs-config-pihliberia pull request #129
Opened 2024-12-13 16:34 UTC by tommyiversonj

This request is about the Liberia NCD EMR and intends to reproduce the UI structure used in the Sierra Leone NCD EMR.
Steps Undertaken:

- The current ncd-adult-followup.xml form for Liberia was renamed to retired

- Created new forms:
     ncd-adult-followup.xml
     section-hypertension.xml
     section-ncd-followup.xml.

- Reused source code from the Sierra Leone NCD implementation for the newly created forms.

Based on this information, I would like to confirm if the steps I have taken are correct and aligned with the intended process. Additionally, I welcome any feedback and support for modification.

I didn't work in any of
pihemr:
- configuration/encountertypes/encounterTypes.csv 
- configuration/pih/scripts/visit/encounterTypeConfig.js

2024-12-17 15:57 UTC, lnball commented
@tommyiversonj   See comments:  https://pihemr.atlassian.net/browse/LIB-319

2024-12-17 15:57 UTC, lnball requested changes

2024-12-17 15:57 UTC, lnball commented on configuration/pih/htmlforms/retired/ncd-adult-followup.xml
Don't move to retired

2024-12-17 15:57 UTC, lnball commented on configuration/pih/htmlforms/ncd-adult-followup.xml
Don't delete.  Rename to ncd-adult-followup_v1.0.xml

2024-12-17 15:57 UTC, lnball commented on configuration/pih/htmlforms/section-hypertension.xml
Is this from Sierra Leone?

2024-12-17 15:57 UTC, lnball commented on configuration/pih/htmlforms/section-ncd-followup.xml
Maybe this should be a section?

2024-12-18 13:02 UTC, tommyiversonj commented on configuration/pih/htmlforms/section-hypertension.xml
@lnball Yes! Just using has a sample

2025-01-29 15:52 UTC, closed without merging